version: 2

builds:
  - main: ./cmd/kvweb
    binary: kvweb
    env:
      - CGO_ENABLED=0
    ldflags:
      - -X main.version={{ .Version }} -X main.commit={{ .ShortCommit }}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - formats:
      - tar.gz
    name_template: "kvweb_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

dockers:
  - image_templates:
      - "ghcr.io/natrimmer/kvweb:{{ .Version }}-amd64"
    use: buildx
    goarch: amd64
    dockerfile: Dockerfile.goreleaser
    build_flag_templates:
      - "--platform=linux/amd64"
  - image_templates:
      - "ghcr.io/natrimmer/kvweb:{{ .Version }}-arm64"
    use: buildx
    goarch: arm64
    dockerfile: Dockerfile.goreleaser
    build_flag_templates:
      - "--platform=linux/arm64"

docker_manifests:
  - name_template: "ghcr.io/natrimmer/kvweb:{{ .Version }}"
    image_templates:
      - "ghcr.io/natrimmer/kvweb:{{ .Version }}-amd64"
      - "ghcr.io/natrimmer/kvweb:{{ .Version }}-arm64"
  - name_template: "ghcr.io/natrimmer/kvweb:latest"
    image_templates:
      - "ghcr.io/natrimmer/kvweb:{{ .Version }}-amd64"
      - "ghcr.io/natrimmer/kvweb:{{ .Version }}-arm64"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
